-- 0218 — Tenant-index backfill (docs/27 R1-1, investment-audit finding AUD-ARC-01).
-- RLS (0002_rls.sql) puts a tenant_id predicate on EVERY query against a tenant-scoped table; 132 such
-- tables had no index whose LEADING column is tenant_id, so per-tenant reads seq-scanned and degrade
-- non-linearly under concurrency. This adds the minimum uniform cover: a plain (tenant_id) btree per
-- uncovered table. Generated from live introspection over the applied migration set (PGlite), names
-- collision-checked against pg_indexes. Idempotent (IF NOT EXISTS); plain CREATE (not CONCURRENTLY) is
-- deliberate — current data volumes make the lock window trivial; revisit if a large tenant lands first.
-- The 'tenant-idx' cutover harness re-runs this introspection in CI and fails on ANY uncovered table,
-- so a new tenant-scoped table cannot ship without a tenant-leading index (no grandfathering).
-- Post-merge addition (docs/27 R1-1): journey_steps arrived from the docs/25-crm series (0212_journeys)
-- without a tenant-leading index — caught by the tenant-idx guard on the main merge.
-- 2026-07-03 incident note: production aborted this migration with 42P01 — its DB predates one of the
-- historical duplicate-number/renumber events and is missing table(s) fresh DBs have (first tripwire:
-- tip_distribution_lines, healed by 0230). Each index is therefore guarded on table existence
-- (to_regclass): identical result where every table exists (all CI/dev DBs — the tenant-idx harness
-- still proves full coverage there), skip-not-crash where prod's catalog has gaps. See
-- docs/ops/drizzle-migration-debt.md.
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY[
    'abandoned_carts',
    'access_reviews',
    'account_groups',
    'api_keys',
    'approval_actions',
    'ar_dunning_log',
    'ar_invoices',
    'asset_meters',
    'asset_movements',
    'asset_revaluations',
    'automation_campaigns',
    'bank_statement_lines',
    'bom_submission_lines',
    'bom_submissions',
    'budget_drivers',
    'budget_scenarios',
    'buffet_package_items',
    'campaign_reads',
    'cash_movements',
    'channel_adapters',
    'channel_webhook_events',
    'close_run_steps',
    'combo_components',
    'connector_syncs',
    'connectors',
    'consol_elimination_rules',
    'cust_bom',
    'cust_bom_lines',
    'cust_prod_runs',
    'cust_stock_log',
    'cust_variance',
    'customer_inventory',
    'customer_items',
    'delivery_orders',
    'depreciation_lines',
    'dine_in_order_items',
    'doc_counters_tenant',
    'einvoice_config',
    'etax_submissions',
    'floor_zones',
    'forecast_lines',
    'fraud_risks',
    'gift_card_txns',
    'gift_cards',
    'gl_audit_log',
    'governance_oversight',
    'ic_settlements',
    'ic_transactions',
    'invoice_match_results',
    'kitchen_stations',
    'labor_alerts',
    'leases',
    'leave_balances',
    'loyalty_mission_progress',
    'loyalty_privilege_claims',
    'loyalty_privileges',
    'loyalty_referrals',
    'loyalty_tier_history',
    'loyalty_tiers',
    'loyalty_txn',
    'loyalty_wheel_segments',
    'maintenance_wo_lines',
    'menu_item_modifier_groups',
    'menu_recipe_lines',
    'migration_jobs',
    'modifier_options',
    'my_customers',
    'my_purchase_orders',
    'my_suppliers',
    'order_delivery_details',
    'orders',
    'payment_intents',
    'payment_refunds',
    'payment_terminals',
    'payslips',
    'pending_orders',
    'performance_obligations',
    'pick_list_lines',
    'pick_waves',
    'pm_schedules',
    'pos_check_splits',
    'pos_held_orders',
    'pos_member_ledger',
    'pos_overrides',
    'pos_return_items',
    'pos_returns',
    'posting_rules',
    'prepaid_schedules',
    'price_list',
    'price_rules',
    'pricing_rules',
    'project_baselines',
    'project_change_orders',
    'project_entries',
    'project_health_snapshots',
    'project_milestones',
    'project_risks',
    'project_tasks',
    'project_template_items',
    'promo_audience_rules',
    'promo_redemptions',
    'promotion_items',
    'reason_codes',
    'receipt_prints',
    'recurring_journals',
    'refund_liability',
    'report_subscriptions',
    'rev_rec_lines',
    'rfqs',
    'rma_lines',
    'rmas',
    'routing_operations',
    'sales_returns',
    'settlement_batches',
    'shipments',
    'subscriptions',
    'supplier_quotes',
    'supplier_scorecards',
    'survey_responses',
    'table_sessions',
    'tax_invoice_lines',
    'till_sessions',
    'time_clock',
    'tip_distribution_lines',
    'users',
    'whistleblower_cases',
    'wht_cert_lines',
    'work_centers',
    'work_order_components',
    'work_order_operations',
    'workflow_steps',
    'xz_report_denominations',
    'journey_steps'
  ] LOOP
    IF to_regclass('public.' || t) IS NOT NULL THEN
      EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (tenant_id)', 'idx_' || t || '_tenant', t);
    END IF;
  END LOOP;
END $$;
