import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { eq, desc, ilike, or } from 'drizzle-orm';
import { DRIZZLE, type DrizzleDb } from '../../database/database.module';
import { controlTestRuns, controlFindings, auditLog } from '../../database/schema';
import type { JwtUser } from '../../common/decorators';

// GRC-1 / ITGC-MON-01 — Control Console (auditor-facing). Surfaces the full RCM control catalogue (platform
// reference data, generated by compliance/build_rcm.py --json into compliance/rcm-catalog.json), the census
// summary, and — per tenant — the recorded test-of-effectiveness (ToE) runs against each control, plus any
// linked continuous-controls-monitoring (CCM) findings and recent tamper-evident audit-log evidence. The
// catalogue is loaded ONCE at module init; test-run reads/writes are tenant-scoped by RLS.

export interface RcmControl {
  control_id: string; cycle: string; category: string; fsli: string; risk: string; assertion: string;
  description: string; prev_det: string; nature: string; frequency: string; owner: string; coso: string;
  code_reference: string; tod: string; toe: string; evidence: string; status: string;
}
interface RcmCatalog { generated_from?: string; date?: string; census?: any; controls: RcmControl[] }

const RESULTS = ['pass', 'fail', 'na'] as const;

// Locate compliance/rcm-catalog.json by walking up from the compiled module dir (apps/api/dist/modules/
// control-console → repo root) and, as a fallback, from the process cwd. Returns [] if not found so a
// partial harness / mis-deploy degrades gracefully rather than crashing at boot.
function loadCatalog(): RcmControl[] {
  const tries: string[] = [];
  let dir = __dirname;
  for (let i = 0; i < 9; i++) { tries.push(join(dir, 'compliance', 'rcm-catalog.json')); dir = dirname(dir); }
  tries.push(join(process.cwd(), 'compliance', 'rcm-catalog.json'));
  tries.push(join(process.cwd(), '..', '..', 'compliance', 'rcm-catalog.json'));
  for (const p of tries) {
    try {
      if (existsSync(p)) {
        const parsed = JSON.parse(readFileSync(p, 'utf8')) as RcmCatalog;
        if (Array.isArray(parsed?.controls)) return parsed.controls;
      }
    } catch { /* try next candidate */ }
  }
  return [];
}

@Injectable()
export class ControlConsoleService {
  private readonly catalog: RcmControl[] = loadCatalog();
  private readonly byId = new Map(this.catalog.map((c) => [c.control_id, c]));

  constructor(@Inject(DRIZZLE) private readonly db: DrizzleDb) {}

  private census() {
    const byStatus: Record<string, number> = {};
    const byFamily: Record<string, number> = {};
    for (const c of this.catalog) {
      byStatus[c.status] = (byStatus[c.status] ?? 0) + 1;
      byFamily[c.cycle] = (byFamily[c.cycle] ?? 0) + 1;
    }
    return { total: this.catalog.length, by_status: byStatus, by_family: byFamily };
  }

  // GET /api/controls/rcm — the catalogue: every control (17 fields), the family roll-up (with per-status
  // counts), and the census summary.
  rcm() {
    const fam = new Map<string, { family: string; total: number; by_status: Record<string, number> }>();
    for (const c of this.catalog) {
      const f = fam.get(c.cycle) ?? { family: c.cycle, total: 0, by_status: {} };
      f.total += 1;
      f.by_status[c.status] = (f.by_status[c.status] ?? 0) + 1;
      fam.set(c.cycle, f);
    }
    return {
      census: this.census(),
      families: [...fam.values()].sort((a, b) => a.family.localeCompare(b.family)),
      controls: this.catalog,
    };
  }

  private isCcmControl(c: RcmControl) {
    return c.cycle === 'Monitoring' || /control_findings|controls\.service|CCM|continuous.controls/i.test(c.code_reference);
  }

  // GET /api/controls/rcm/:controlId — the control's 17 RCM fields + its latest/historical ToE test-runs
  // (tenant-scoped), any linked CCM findings (for monitoring controls), and recent audit-log evidence.
  async rcmDetail(controlId: string) {
    const control = this.byId.get(controlId);
    if (!control) throw new NotFoundException({ code: 'CONTROL_NOT_FOUND', message: `Unknown control ${controlId}`, messageTh: 'ไม่พบรหัสการควบคุม' });
    const db = this.db;

    const runs = await db.select().from(controlTestRuns)
      .where(eq(controlTestRuns.controlId, controlId))
      .orderBy(desc(controlTestRuns.runAt)).limit(50);
    const testRuns = runs.map((r: any) => this.fmtRun(r));

    let ccmFindings: any[] = [];
    if (this.isCcmControl(control)) {
      const f = await db.select().from(controlFindings)
        .where(eq(controlFindings.status, 'open'))
        .orderBy(desc(controlFindings.detectedAt)).limit(50);
      ccmFindings = f.map((r: any) => ({ id: Number(r.id), control_key: r.controlKey, severity: r.severity, entity_ref: r.entityRef, detail: r.detail, amount: r.amount != null ? Number(r.amount) : null, status: r.status, detected_at: r.detectedAt }));
    }

    // Recent tamper-evident audit-log rows tied to this control (evidence): rows whose entity_id is the
    // control id, or whose action/meta references it. RLS scopes to the caller's tenant.
    const auditRows = await db.select().from(auditLog)
      .where(or(eq(auditLog.entityId, controlId), ilike(auditLog.action, `%/rcm/${controlId}/%`)))
      .orderBy(desc(auditLog.ts)).limit(20);
    const auditEvidence = auditRows.map((r: any) => ({ id: Number(r.id), ts: r.ts, actor: r.actor, action: r.action, entity: r.entity, entity_id: r.entityId, status: r.status }));

    return {
      control,
      test_runs: testRuns,
      latest_test_run: testRuns[0] ?? null,
      ccm_findings: ccmFindings,
      audit_evidence: auditEvidence,
    };
  }

  private fmtRun(r: any) {
    return {
      id: Number(r.id), control_id: r.controlId, result: r.result, harness: r.harness,
      checks_passed: r.checksPassed != null ? Number(r.checksPassed) : null,
      checks_total: r.checksTotal != null ? Number(r.checksTotal) : null,
      evidence_ref: r.evidenceRef, notes: r.notes, recorded_by: r.recordedBy, run_at: r.runAt,
    };
  }

  // POST /api/controls/rcm/:controlId/test-run — record a ToE run against a known control.
  async recordTestRun(user: JwtUser, controlId: string, dto: { result?: string; harness?: string; checks_passed?: number; checks_total?: number; evidence_ref?: string; notes?: string }) {
    if (!this.byId.has(controlId)) throw new NotFoundException({ code: 'CONTROL_NOT_FOUND', message: `Unknown control ${controlId}`, messageTh: 'ไม่พบรหัสการควบคุม' });
    const result = (RESULTS as readonly string[]).includes(dto.result ?? '') ? dto.result! : 'pass';
    const [row] = await this.db.insert(controlTestRuns).values({
      tenantId: user.tenantId ?? null, controlId, result,
      harness: dto.harness ?? null,
      checksPassed: dto.checks_passed ?? null, checksTotal: dto.checks_total ?? null,
      evidenceRef: dto.evidence_ref ?? null, notes: dto.notes ?? null, recordedBy: user.username,
    }).returning();
    return this.fmtRun(row);
  }
}
