// Enterprise Asset Management (EAM) — maintenance on top of the fixed-asset register: corrective &
// preventive work orders, preventive-maintenance schedules (time- or meter-based) and meter readings.
// Every table carries tenant_id → the RLS loop scopes them. Maintenance cost posts to the GL/AP via
// FinanceService (Dr 5700 Repairs & Maintenance / Cr 2000 AP) on work-order completion.
import { pgTable, bigserial, bigint, text, numeric, date, timestamp, index, unique } from 'drizzle-orm/pg-core';
import { tenants } from './tenants';
import { fixedAssets } from './assets';

export const maintenanceWorkOrders = pgTable('maintenance_work_orders', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  tenantId: bigint('tenant_id', { mode: 'number' }).references(() => tenants.id),
  woNo: text('wo_no').notNull(),
  assetId: bigint('asset_id', { mode: 'number' }).references(() => fixedAssets.id),
  assetNo: text('asset_no'),
  type: text('type').notNull().default('corrective'), // corrective | preventive | inspection
  priority: text('priority').default('medium'),       // low | medium | high
  status: text('status').notNull().default('open'),   // open | in_progress | completed | cancelled
  description: text('description'),
  scheduledDate: date('scheduled_date'),
  startedAt: timestamp('started_at', { withTimezone: true }),
  completedDate: date('completed_date'),
  vendorName: text('vendor_name'),
  costEstimate: numeric('cost_estimate', { precision: 14, scale: 2 }).default('0'),
  actualCost: numeric('actual_cost', { precision: 14, scale: 2 }).default('0'),
  downtimeHours: numeric('downtime_hours', { precision: 10, scale: 2 }).default('0'),
  meterReading: numeric('meter_reading', { precision: 18, scale: 2 }),
  apTxnNo: text('ap_txn_no'),                          // AP payable for the maintenance cost (AP-…)
  pmScheduleId: bigint('pm_schedule_id', { mode: 'number' }), // set when auto-generated by a PM schedule
  createdBy: text('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (t) => ({ uqWo: unique('uq_mwo_no').on(t.tenantId, t.woNo), byAsset: index('idx_mwo_asset').on(t.assetId), byStatus: index('idx_mwo_status').on(t.status) }));

export const pmSchedules = pgTable('pm_schedules', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  tenantId: bigint('tenant_id', { mode: 'number' }).references(() => tenants.id),
  assetId: bigint('asset_id', { mode: 'number' }).references(() => fixedAssets.id),
  assetNo: text('asset_no'),
  name: text('name').notNull(),
  intervalDays: bigint('interval_days', { mode: 'number' }),     // time-based cadence
  meterInterval: numeric('meter_interval', { precision: 18, scale: 2 }), // meter-based cadence (optional)
  lastServiceDate: date('last_service_date'),
  lastServiceMeter: numeric('last_service_meter', { precision: 18, scale: 2 }).default('0'),
  nextDueDate: date('next_due_date'),
  active: text('active').default('true'),
  createdBy: text('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (t) => ({ byAsset: index('idx_pm_asset').on(t.assetId) }));

export const assetMeters = pgTable('asset_meters', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  tenantId: bigint('tenant_id', { mode: 'number' }).references(() => tenants.id),
  assetId: bigint('asset_id', { mode: 'number' }).references(() => fixedAssets.id),
  assetNo: text('asset_no'),
  readingDate: date('reading_date'),
  meterValue: numeric('meter_value', { precision: 18, scale: 2 }).notNull(),
  note: text('note'),
  createdBy: text('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (t) => ({ byAsset: index('idx_meter_asset').on(t.assetId) }));
